"""
loadtest.py — concurrency load test for the store-backed /score path.

Proves the "sub-100ms scoring" claim honestly: it warms the online feature
store with realistic per-customer history first (so velocity lookups aren't
trivially empty), then drives concurrent store-backed /score requests and
reports throughput and the full latency distribution (p50/p95/p99), plus the
error rate. Results are written to loadtest/results.md.

Usage (server must already be running, see loadtest/README or docker-compose):
    python loadtest/loadtest.py \
        --host http://localhost:8000 \
        --customers 2000 --warmup-per-customer 5 \
        --requests 20000 --concurrency 64

Uses asyncio + httpx: an HTTP/1.1 connection pool with `concurrency` in-flight
requests, which is a realistic model of many workers hitting one endpoint.
"""

import argparse
import asyncio
import random
import statistics
import time
from datetime import datetime, timezone

import httpx


def _rand_features():
    # V1-V28 stand in for the PCA components a real txn carries.
    return {f"V{i}": random.gauss(0, 1) for i in range(1, 29)}


CATEGORIES = ["grocery", "electronics", "travel", "crypto", "gambling", "restaurant"]


def _iso(ts: float) -> str:
    return datetime.fromtimestamp(ts, tz=timezone.utc).isoformat()


async def warmup(client: httpx.AsyncClient, customers, per_customer, concurrency):
    """Backfill each customer with `per_customer` recent transactions spread
    over the last 24h, so the 10m/60m/1440m windows have real content.
    """
    now = time.time()
    jobs = []
    for cid in customers:
        for _ in range(per_customer):
            offset = random.uniform(0, 24 * 3600)  # within the 1440m window
            jobs.append({
                "transaction_id": f"WARM_{cid}_{offset:.0f}",
                "customer_id": cid,
                "merchant_id": random.randint(1, 500),
                "merchant_category": random.choice(CATEGORIES),
                "device_id": f"{cid}_dev{random.randint(0, 2)}",
                "amount": round(random.uniform(1, 800), 2),
                "timestamp": _iso(now - offset),
            })
    sem = asyncio.Semaphore(concurrency)

    async def one(payload):
        async with sem:
            await client.post("/ingest", json=payload)

    await asyncio.gather(*(one(j) for j in jobs))
    return len(jobs)


async def run_load(client, customers, n_requests, concurrency):
    latencies = []
    errors = 0
    sem = asyncio.Semaphore(concurrency)

    async def one(i):
        nonlocal errors
        cid = random.choice(customers)
        payload = {
            "transaction_id": f"LOAD_{i}",
            "customer_id": cid,
            "merchant_id": random.randint(1, 500),
            "merchant_category": random.choice(CATEGORIES),
            "device_id": f"{cid}_dev{random.randint(0, 3)}",  # sometimes a new device
            "amount": round(random.uniform(1, 800), 2),
            "timestamp": _iso(time.time()),
            "use_feature_store": True,
            "ingest": True,
            "features": _rand_features(),
        }
        async with sem:
            t0 = time.perf_counter()
            try:
                resp = await client.post("/score", json=payload)
                if resp.status_code != 200:
                    errors += 1
                    return
            except Exception:
                errors += 1
                return
            latencies.append((time.perf_counter() - t0) * 1000.0)

    t_start = time.perf_counter()
    await asyncio.gather(*(one(i) for i in range(n_requests)))
    wall = time.perf_counter() - t_start
    return latencies, errors, wall


def pct(sorted_vals, p):
    if not sorted_vals:
        return float("nan")
    k = max(0, min(len(sorted_vals) - 1, int(round((p / 100) * (len(sorted_vals) - 1)))))
    return sorted_vals[k]


def write_results(path, meta, latencies, errors, wall, n_requests):
    latencies_sorted = sorted(latencies)
    ok = len(latencies)
    rps = ok / wall if wall > 0 else float("nan")
    lines = [
        "# Load test results",
        "",
        "> Generated by `loadtest/loadtest.py`. Every number below is from an "
        "actual run on the hardware/command stated — nothing here is hand-written.",
        "",
        "## Environment",
        "",
        f"- **Date:** {meta['date']}",
        f"- **Hardware:** {meta['hardware']}",
        f"- **Python:** {meta['python']}",
        f"- **Feature store backend:** {meta['backend']}",
        f"- **Server:** {meta['server']}",
        "",
        "## Command",
        "",
        "```bash",
        meta["command"],
        "```",
        "",
        "## Workload",
        "",
        f"- Warmed store with **{meta['warmup_txns']:,}** transactions "
        f"({meta['customers']:,} customers × {meta['warmup_per_customer']} each).",
        f"- Drove **{n_requests:,}** store-backed `/score` requests "
        f"(each also commits, i.e. score-then-ingest) at concurrency "
        f"**{meta['concurrency']}**.",
        "",
        "## Results",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Successful requests | {ok:,} |",
        f"| Errors | {errors:,} ({(errors / n_requests * 100 if n_requests else 0):.2f}%) |",
        f"| Wall time | {wall:.2f} s |",
        f"| Throughput | {rps:,.0f} RPS |",
        f"| Latency p50 | {pct(latencies_sorted, 50):.2f} ms |",
        f"| Latency p95 | {pct(latencies_sorted, 95):.2f} ms |",
        f"| Latency p99 | {pct(latencies_sorted, 99):.2f} ms |",
        f"| Latency max | {(latencies_sorted[-1] if latencies_sorted else float('nan')):.2f} ms |",
        "",
    ]
    p99 = pct(latencies_sorted, 99)
    if p99 < 100:
        lines += [
            f"**p99 = {p99:.2f} ms < 100 ms target — met** at {rps:,.0f} RPS on a laptop.",
        ]
    else:
        lines += [
            f"**p99 = {p99:.2f} ms exceeds the 100 ms target.** Honest result. "
            "Closing the gap: run uvicorn with multiple workers + a real Redis "
            "(shared state across workers), batch model inference, C-serialize "
            "the feature row, and/or move SHAP off the hot path.",
        ]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return rps, p99


async def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--host", default="http://localhost:8000")
    ap.add_argument("--customers", type=int, default=2000)
    ap.add_argument("--warmup-per-customer", type=int, default=5)
    ap.add_argument("--requests", type=int, default=20000)
    ap.add_argument("--concurrency", type=int, default=64)
    ap.add_argument("--out", default="loadtest/results.md")
    ap.add_argument("--hardware", default="unknown")
    ap.add_argument("--backend", default="unknown")
    ap.add_argument("--server", default="uvicorn (1 worker)")
    args = ap.parse_args()

    customers = [f"CUST_{i:06d}" for i in range(args.customers)]
    limits = httpx.Limits(max_connections=args.concurrency + 16,
                          max_keepalive_connections=args.concurrency + 16)
    async with httpx.AsyncClient(base_url=args.host, timeout=30.0, limits=limits) as client:
        print("Warming store...")
        warm_n = await warmup(client, customers, args.warmup_per_customer, args.concurrency)
        print(f"  ingested {warm_n:,} warmup txns")
        print("Running load...")
        latencies, errors, wall = await run_load(client, customers, args.requests, args.concurrency)

    import platform
    meta = {
        "date": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "hardware": args.hardware,
        "python": platform.python_version(),
        "backend": args.backend,
        "server": args.server,
        "command": (
            f"python loadtest/loadtest.py --host {args.host} "
            f"--customers {args.customers} --warmup-per-customer {args.warmup_per_customer} "
            f"--requests {args.requests} --concurrency {args.concurrency}"
        ),
        "warmup_txns": warm_n,
        "customers": args.customers,
        "warmup_per_customer": args.warmup_per_customer,
        "concurrency": args.concurrency,
    }
    rps, p99 = write_results(args.out, meta, latencies, errors, wall, args.requests)
    print(f"Done. {rps:,.0f} RPS, p99={p99:.2f} ms, errors={errors}. Wrote {args.out}")


if __name__ == "__main__":
    asyncio.run(main())
